"""empty message

Revision ID: 121242030536
Revises: 2f7013cbb432
Create Date: 2022-01-16 11:00:17.045765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121242030536'
down_revision = '2f7013cbb432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
