"""empty message

Revision ID: 2115f7b275c8
Revises: 2c5189ef0b0f
Create Date: 2022-01-20 15:14:33.220272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2115f7b275c8'
down_revision = '2c5189ef0b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
