"""Added foreignkey from BookModel to UserModel

Revision ID: 21306bd16d33
Revises: d633a98811db
Create Date: 2022-01-15 15:35:13.587412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21306bd16d33'
down_revision = 'd633a98811db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('child_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'book', 'user', ['child_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'child_id')
    # ### end Alembic commands ###
