"""empty message

Revision ID: 29b7469d0bae
Revises: 6b7dd0c99d01
Create Date: 2022-01-17 22:26:47.945129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b7469d0bae'
down_revision = '6b7dd0c99d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
