"""empty message

Revision ID: 41c0af345147
Revises: 2ccc2ac8d751
Create Date: 2022-01-15 18:13:27.597357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c0af345147'
down_revision = '2ccc2ac8d751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
