"""empty message

Revision ID: 510a13bbf5cb
Revises: 7e1b3d000747
Create Date: 2022-01-15 16:07:33.873632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '510a13bbf5cb'
down_revision = '7e1b3d000747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('user', postgresql.UUID(), nullable=True))
    op.drop_constraint('book_user_id_fkey', 'book', type_='foreignkey')
    op.create_foreign_key(None, 'book', 'user', ['user'], ['id'])
    op.drop_column('book', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.create_foreign_key('book_user_id_fkey', 'book', 'user', ['user_id'], ['id'])
    op.drop_column('book', 'user')
    # ### end Alembic commands ###
