"""empty message

Revision ID: 6b7dd0c99d01
Revises: 121242030536
Create Date: 2022-01-16 16:05:08.656340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b7dd0c99d01'
down_revision = '121242030536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('user_id', postgresql.UUID(), nullable=True))
    op.drop_constraint('book_user_fkey', 'book', type_='foreignkey')
    op.create_foreign_key(None, 'book', 'user', ['user_id'], ['id'])
    op.drop_column('book', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('user', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.create_foreign_key('book_user_fkey', 'book', 'user', ['user'], ['id'])
    op.drop_column('book', 'user_id')
    # ### end Alembic commands ###
