"""empty message

Revision ID: 7e1b3d000747
Revises: e3e6142f9860
Create Date: 2022-01-15 15:57:21.533690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1b3d000747'
down_revision = 'e3e6142f9860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
