"""empty message

Revision ID: 86b44af4aa9f
Revises: 29b7469d0bae
Create Date: 2022-01-19 17:37:11.455142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86b44af4aa9f'
down_revision = '29b7469d0bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_image',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('book_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('book', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('book', sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'updated')
    op.drop_column('book', 'created')
    op.drop_table('book_image')
    # ### end Alembic commands ###
