"""Changed foreignkey parameters

Revision ID: 8c7ce339f6ab
Revises: 21306bd16d33
Create Date: 2022-01-15 15:36:47.747418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c7ce339f6ab'
down_revision = '21306bd16d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('user_id', postgresql.UUID(), nullable=True))
    op.drop_constraint('book_child_id_fkey', 'book', type_='foreignkey')
    op.create_foreign_key(None, 'book', 'user', ['user_id'], ['id'])
    op.drop_column('book', 'child_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('child_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.create_foreign_key('book_child_id_fkey', 'book', 'user', ['child_id'], ['id'])
    op.drop_column('book', 'user_id')
    # ### end Alembic commands ###
