"""Changed models classes names

Revision ID: a5180edc2d97
Revises: 8c7ce339f6ab
Create Date: 2022-01-15 15:46:47.602733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5180edc2d97'
down_revision = '8c7ce339f6ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
