"""empty message

Revision ID: c19c8b5fd747
Revises: 628c1261ceb0
Create Date: 2022-01-25 19:23:09.157901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c19c8b5fd747'
down_revision = '628c1261ceb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('book', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('book', 'created')
    op.drop_column('book', 'updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('book', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('book', 'updated_at')
    op.drop_column('book', 'created_at')
    # ### end Alembic commands ###
