"""Deleted Publisher and Author models and added new columns to Book model.

Revision ID: d633a98811db
Revises: 505c6a1a352c
Create Date: 2022-01-14 17:57:20.719556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd633a98811db'
down_revision = '505c6a1a352c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author')
    op.drop_table('publisher')
    op.add_column('book', sa.Column('description', sa.String(), nullable=True))
    op.add_column('book', sa.Column('language', sa.String(), nullable=True))
    op.add_column('book', sa.Column('pages', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'pages')
    op.drop_column('book', 'language')
    op.drop_column('book', 'description')
    op.create_table('publisher',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='publisher_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='publisher_pkey')
    )
    op.create_table('author',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='author_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='author_pkey')
    )
    # ### end Alembic commands ###
