"""empty message

Revision ID: e3e6142f9860
Revises: a5180edc2d97
Create Date: 2022-01-15 15:56:12.812071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e6142f9860'
down_revision = 'a5180edc2d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
